# Generated by Django 4.2.16 on 2025-08-18 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0015_preventivemaintenance_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image file', null=True, upload_to='maintenance_job_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Image after maintenance', null=True, upload_to='maintenance_pm_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Image before maintenance', null=True, upload_to='maintenance_pm_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
    ]
